# Generated by Django 5.2 on 2026-04-04 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_customuser_id_internshiplog'),
        ('api', '0002_alter_customuser_id_internshipplacement_weeklylog_and_more'),
    ]

    operations = [
    ]
