# Generated by Django 5.2 on 2026-04-06 15:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_merge_20260404_2125'),
    ]

    operations = [
        migrations.AddField(
            model_name='internshipplacement',
            name='academic_supervisor',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'academic_supervisor'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='academic_placements', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='internshipplacement',
            name='department',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='internshipplacement',
            name='workplace_supervisor',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'workplace_supervisor'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supervised_placements', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='evaluation',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='internshipplacement',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='internshipplacement',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('active', 'Active'), ('completed', 'Completed'), ('pending', 'Pending')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='supervisorreview',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='weeklylog',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.DeleteModel(
            name='InternshipLog',
        ),
    ]
